incul/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url, include
from django.contrib import admin
from ajax_select import urls as ajax_select_urls

admin.autodiscover()

urlpatterns = patterns('',
                       # Base
                       url(r'^incul/bunpou/$', 'note.views.lessons', name='lessons'),
                       url(r'^incul/bunpou/lesson/(?P<lessonId>\d+)/$', 'note.views.topics', name='topics'),
                       url(r'^incul/bunpou/topic/(?P<topicId>\d+)/$', 'note.views.examples', name='examples'),
                       url(r'^incul/kanji/kanjilist/(?P<lessonId>\d+)/$', 'note.kanjiviews.kanjiList',
                           name='kanjiList'),
                       url(r'^incul/kanji/kanjiwords/(?P<kanjiId>\d+)/$', 'note.kanjiviews.kanjiWords',
                           name='kanjiWords'),
                       url(r'^incul/search/(?P<searchString>\w*)/$', 'note.views.search', name='search'),
                       url(r'^incul/$', 'note.views.lessons', name='home'),

                       #Add views
                       url(r'^incul/addLevel/$', 'note.views.addLevel', name='addLevel'),
                       url(r'^incul/userSettings/$', 'note.views.userSettings', name='userSettings'),
                       url(r'^incul/sensei/(?P<senseiId>\w+){0,1}$', 'note.views.sensei', name='senseis'),
                       url(r'^incul/bunpou/(?P<levelId>\d+)/(?P<lessonId>\d+)/$', 'note.views.lessons',
                           name='lessonsEdit'),
                       url(r'^incul/bunpou/lesson/(?P<lessonId>\d+)/(?P<topicId>\d+)/$', 'note.views.topics',
                           name='topicsEdit'),
                       url(r'^incul/bunpou/topic/(?P<topicId>\d+)/(?P<exampleId>\d+)/$', 'note.views.examples',
                           name='examplesEdit'),
                       url(r'^incul/addBook/$', 'note.views.addBooks', name='addBook'),

                       url(r'^incul/kanji/(?P<lessonId>\d+){0,1}$', 'note.kanjiviews.kanjiLessons',
                           name='kanjiLessons'),
                       url(r'^incul/kanji/kanjilist/(?P<lessonId>\d+)/(?P<kanjiId>\d+)/$', 'note.kanjiviews.kanjiList',
                           name='kanjiEdit'),
                       url(r'^incul/kanji/kanjiwords/(?P<kanjiId>\d+)/(?P<kanjiWordId>\d+)/$',
                           'note.kanjiviews.kanjiWords', name='kanjiWordEdit'),
                       #English Part
                       url(r'^incul/english/(?P<chapterId>\d+){0,1}$', 'note.views.englishWordsChapter',
                           name='englishWordsChapter'),
                       url(r'^incul/english/words/(?P<chapterId>\d+){1}/(?P<wordId>\d+){0,1}$',
                           'note.views.englishWords', name='englishWords'),
                       url(r'^incul/english/training/words/$', 'note.trainingsViews.englishWords',
                           name='englishWordsTraining'),
                       url(r'^incul/english/training/examples/$', 'note.trainingsViews.englishExamples',
                           name='englishExamplesTraining'),
                       #TrainingViews
                       #url(r'^incul/kanji/quizze/(?P<answer>\w*)[/]?$', 'note.trainingsViews.kanjiQuizze',
                       #    name='kanjiQuizze'),
                       url(r'^incul/kanji/quizze/testProcess/$', 'note.trainingsViews.testProcess',
                           name='testProcess'),
                       url(r'^incul/kanji/quizze/$', 'note.trainingsViews.trainingView',
                           name='trainingView'),
                       url(r'^incul/bunpou/training/dictionary/$', 'note.trainingsViews.dictionary',
                           name='dictionaryTraining'),
                       url(r'^incul/bunpou/training/grammar/$', 'note.trainingsViews.grammar', name='grammarTraining'),
                       url(r'^incul/bunpou/training/N3/$', 'note.trainingsViews.shikenN3', name='shikenN3Training'),

                       #Post views
                       url(r'^incul/convert/$', 'note.views.convert', name='convert'),

                       #Admin
                       url('^incul/aadmin/lookups/', include(ajax_select_urls)),
                       url('^incul/aadmin/', include(admin.site.urls)),

                       #Auth urls
                       url(r'^incul/login/$', 'django.contrib.auth.views.login', name='login'),
                       url(r'^incul/logout/$', 'django.contrib.auth.views.logout', name='logout'),
)

note/models.py
# -*- coding: utf-8 -*-
import datetime
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.utils import timezone, importlib
from note.settings import behaviorsClasses


class Sex(models.Model):
    sexName = models.CharField(max_length=10, unique=True)

    class Meta:
        db_table = 'incul_sex'
        ordering = ['sexName', ]

    def __unicode__(self):
        return self.sexName


class UserSettings(models.Model):
    user = models.ForeignKey(User)
    currentKanjiLesson = models.PositiveIntegerField(max_length=5, default=500)
    currentHomeClassChapter = models.PositiveIntegerField(max_length=5, default=500)
    currentLevel = models.ForeignKey('Level')


class Sensei(models.Model):
    fullName = models.CharField(max_length=100)
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    fullNameFurigana = models.CharField(max_length=100)
    firstNameFurigana = models.CharField(max_length=50)
    lastNameFurigana = models.CharField(max_length=50)
    sex = models.ForeignKey('Sex')
    birthday = models.DateField(null=True)
    placeFrom = models.CharField(max_length=100)

    class Meta:
        db_table = 'incul_sensei'
        ordering = ['fullName', 'sex']

    def __unicode__(self):
        return self.fullName

    def get_absolute_url(self):
        return reverse('note.views.sensei', args=[str(self.id)])


class Book(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        db_table = 'incul_book'
        ordering = ['name']

    def __unicode__(self):
        return self.name


class Level(models.Model):
    name = models.CharField(max_length=10, unique=True)
    startPeriod = models.DateField(null=True)
    endPeriod = models.DateField(null=True)

    class Meta:
        db_table = 'incul_level'
        ordering = ['name']

    def __unicode__(self):
        return self.name


class Lesson(models.Model):
    level = models.ForeignKey('Level')
    chapterNumber = models.PositiveIntegerField(max_length=5, null=True)
    book = models.ForeignKey('Book', null=True)
    date = models.DateField(null=False)
    sensei = models.ForeignKey('Sensei')

    class Meta:
        db_table = 'incul_lesson'
        ordering = ['chapterNumber']

    def __str__(self):
        return str(self.chapterNumber)

    def get_absolute_url(self):
        return reverse('note.views.topics', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('note.views.lessons', args=[str(self.level.id), str(self.id)])


class TopicType(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Topic(models.Model):
    lesson = models.ForeignKey('Lesson')
    name = models.CharField(max_length=100)
    description = models.TextField(null=True)
    topicType = models.ForeignKey('TopicType', null=False)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('note.views.examples', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('note.views.topics', args=[str(self.lesson.id), str(self.id)])


class Example(models.Model):
    topic = models.ForeignKey('Topic')
    kanji = models.TextField(null=True)
    furigana = models.TextField(null=True)
    translateEng = models.TextField(null=True)
    translateRus = models.TextField(null=True)

    def __unicode__(self):
        return self.kanji

    def get_edit_url(self):
        return reverse('note.views.examples', args=[str(self.topic.id), str(self.id)])


class KanjiLesson(models.Model):
    sensei = models.ForeignKey('Sensei')
    date = models.DateField(null=True)
    book = models.ForeignKey('Book', null=True)

    class Meta:
        db_table = 'incul_kanjilesson'
        ordering = ['date']

    def __unicode__(self):
        return self.date

    def get_absolute_url(self):
        return reverse('note.kanjiviews.kanjiList', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('note.kanjiviews.kanjiLessons', args=[str(self.id)])


class Kanji(models.Model):
    lesson = models.ForeignKey('KanjiLesson')
    number = models.PositiveIntegerField(max_length=5, null=True)
    symbol = models.CharField(max_length=5)
    reading = models.CharField(max_length=30)
    meaning = models.CharField(max_length=100)

    def __unicode__(self):
        return self.symbol

    class Meta:
        db_table = 'incul_kanji'
        ordering = ['number']

    def get_absolute_url(self):
        #if not hasattr(self, 'absoluteUrl'):
        #    self.absoluteUrl = reverse('note.kanjiviews.kanjiWords', args=[str(self.id)])
        #return self.absoluteUrl
        return reverse('note.kanjiviews.kanjiWords', args=[str(self.id)])

    def get_edit_url(self):
        #if not hasattr(self, 'editUrl'):
        #    self.editUrl = reverse('note.kanjiviews.kanjiList', args=[str(self.lesson.pk), str(self.id)])
        #return self.editUrl
        return reverse('note.kanjiviews.kanjiList', args=[str(self.lesson.pk), str(self.id)])


class KanjiWord(models.Model):
    relatedKanji = models.ForeignKey('Kanji')
    writing = models.CharField(max_length=30)
    reading = models.CharField(max_length=30)
    translation = models.CharField(max_length=30)
    shikenLevel = models.PositiveIntegerField(max_length=1, null=True)

    class Meta:
        db_table = 'incul_kanjiword'
        ordering = ['relatedKanji']

    def get_edit_url(self):
        return reverse('note.kanjiviews.kanjiWords', args=[str(self.relatedKanji.pk), str(self.id)])

    def __unicode__(self):
        return self.writing


class KanjiQuizze(models.Model):
    sessionKey = models.CharField(max_length=30, null=False)
    content = models.CharField(max_length=30, null=False)
    answer = models.CharField(max_length=30, null=False)
    date = models.DateField(null=False)

    class Meta:
        db_table = 'incul_kanjquizze'
        ordering = ['date']


class TrainingAnswer(models.Model):
    sessionKey = models.CharField(max_length=30, null=False)
    content = models.CharField(max_length=300, null=False)
    answer = models.CharField(max_length=300, null=False)
    date = models.DateField(null=False)

    class Meta:
        db_table = 'incul_trainingAnswer'
        ordering = ['date']


class EnglishWordsChapter(models.Model):
    contentName = models.CharField(max_length=20)
    book = models.ForeignKey('Book', null=True)
    date = models.DateField(null=False, default=datetime.date.today)

    class Meta:
        ordering = ['date']

    def get_absolute_url(self):
        return reverse('note.views.englishWords', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('note.views.englishWordsChapter', args=[str(self.id)])


class EnglishWord(models.Model):
    chapter = models.ForeignKey('EnglishWordsChapter', null=False)
    verbEng = models.CharField(max_length=30, null=True)
    verbJp = models.CharField(max_length=100, null=True)
    nounEng = models.CharField(max_length=30, null=True)
    nounJp = models.CharField(max_length=100, null=True)
    adjEng = models.CharField(max_length=30, null=True)
    adjJp = models.CharField(max_length=100, null=True)
    exampleEng = models.CharField(max_length=300, null=True)
    exampleJp = models.CharField(max_length=300, null=True)

    def get_edit_url(self):
        return reverse('note.views.englishWords', args=[str(self.chapter.id), str(self.id)])


class TestEntity(models.Model):
    testSuit = models.ForeignKey('TestSuit')
    entityId = models.PositiveIntegerField(null=False)
    points = models.IntegerField(default=0)

    class Meta:
        db_table = 'incul_TEST_entity'


class TestCurrentQuestion(models.Model):
    creationDate = models.DateTimeField(null=False, default=timezone.now())
    question = models.CharField(max_length=100, null=False)
    answer = models.CharField(max_length=100, null=False)
    hint = models.CharField(max_length=200, null=False)
    entityId = models.ForeignKey('TestEntity', null=True)

    def save(self, *args, **kwargs):
        self.creationDate = timezone.now()
        super(TestCurrentQuestion, self).save(*args, **kwargs)

    class Meta:
        db_table = 'incul_TEST_currentQuestion'
        ordering = ['creationDate']


class TestSuit(models.Model):
    creationDate = models.DateTimeField(null=False, default=timezone.now())
    currentStep = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User)
    isActive = models.BooleanField(default=False)
    testingEntityCT = models.ForeignKey(ContentType, null=False)
    points = models.IntegerField(default=0)
    currentQuestion = models.OneToOneField('TestCurrentQuestion', related_name='testSuit')
    topic = models.ForeignKey('TestTopics')

    class Meta:
        ordering = ['creationDate']
        db_table = 'incul_TEST_suit'

    @classmethod
    def create(cls):
        ts = cls()
        ts.creationDate = timezone.now()
        ts.currentQuestion = TestCurrentQuestion()
        return ts

    def save(self, *args, **kwargs):
        self.currentQuestion.save()
        self.currentQuestion = self.currentQuestion
        super(TestSuit, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.currentQuestion.delete()
        super(TestSuit, self).delete(*args, **kwargs)


class TestTopics(models.Model):
    topicCT = models.ForeignKey(ContentType, null=False)
    title = models.CharField(max_length=30, null=False)
    questionField = models.CharField(max_length=30, null=True)
    answerField = models.CharField(max_length=30, null=True)
    hintField = models.CharField(max_length=30, null=True)
    testBehaviorClass = models.CharField(max_length=30, null=True)

templates/base.html
{% load bootstrap3 %}
{% load staticfiles %}
{% load ajax_extra %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    {# Load CSS and JavaScript #}
    <script src="{% bootstrap_jquery_url %}"></script>
    <script src="{% static "jquery-ui/js/jquery-ui-1.10.4.custom.js" %}"></script>
    <script src="{% static "js/baseNav.js" %}"></script>
    <script src="{% static "js/cookie.js" %}"></script>
    {% block custom_inculde %}
    {% endblock %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block title %}
        <title>Inculgakko</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    <link rel="stylesheet" href="{% static "jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css" %}">
    {# {% ajax %} #}
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
</head>

<body>
<div>
    <img id="logo" src="{% static "media/images/logo.jpg" %}" alt="Logo"/>
</div>
<div class="userCorner">
    {% block userCorner %}
        {% if user.is_authenticated %}
            <div class="userCornerText">
                Logged as <span>{{ user }}</span>. <a href="{% url 'logout' %}">Logout</a>
            </div>
        {% endif %}
    {% endblock %}
</div>
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% block topnav-left %}
                {% endblock %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <form id="searchField" class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                </form>
                {% block topnav-right %}
                {% endblock %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'note.views.addLevel' %}"><span
                                    class="glyphicon glyphicon-star-empty"></span> Levels</a>
                        </li>
                        <li>
                            <a href="{% url 'note.views.sensei' %}"><span class="glyphicon glyphicon-user"></span>
                                Senseis</a>
                        </li>
                        <li>
                            <a href="{% url 'note.views.addBooks' %}"><span class="glyphicon glyphicon-book"></span>
                                Books</a>
                        </li>
                        <li>
                            <a href="{% url 'note.views.userSettings' %}"><span class="glyphicon glyphicon-eye-open"></span>
                                User Settings</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Class<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'note.views.lessons' %}"><span class="glyphicon glyphicon-comment"></span>
                            Bunpou</a></li>
                        <li><a href="{% url 'note.kanjiviews.kanjiLessons' %}"><span
                                class="glyphicon glyphicon-pencil"></span> Kanji</a></li>
                        <li><a href="{% url 'note.views.englishWordsChapter' %}"><span
                                class="glyphicon glyphicon-font"></span> English</a></li>
                    </ul>
                </li>
            </ul>
            </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
{% block leftnav %}
    <nav class="leftnav" role="main">
        <ul id="sidenav01" class="accordion nav nav-department nav-tabs nav-stacked">
            <li>
                <a href="{% url 'note.views.addLevel' %}"><span class="glyphicon glyphicon-star-empty"></span>
                    Levels</a>
            </li>
            <li>
                <a href="{% url 'note.views.sensei' %}"><span class="glyphicon glyphicon-user"></span> Senseis</a>
            </li>
            <li>
                <a href="{% url 'note.views.addBooks' %}"><span class="glyphicon glyphicon-book"></span> Books</a>
            </li>
        </ul>
    </nav>
{% endblock %}







<section id="main">
    {% block content %}
    {% endblock %}
</section>


</body>
</html>

templates/basebunpou.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block topnav-left %}

    <li><a href="{% url 'note.views.lessons' %}"><span class="glyphicon glyphicon-home"></span>Home</a></li>
    <li><a><span class="glyphicon glyphicon-stats"></span> {{ content.levelName }}</a></li>

    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Training<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <a href="{% url 'note.trainingsViews.dictionary' %}"><span class="glyphicon glyphicon-book"></span>
                    Dictionary</a>
            </li>
            <li>
                <a href="{% url 'note.trainingsViews.grammar' %}"><span class="glyphicon glyphicon-font"></span> Bunpou</a>
            </li>
            <li>
                <a href="{% url 'note.trainingsViews.shikenN3' %}"><span class="glyphicon glyphicon-tower"></span>
                    N3</a>
            </li>
        </ul>
    </li>
{% endblock %}

{% block topnav-right %}
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Level<b class="caret"></b></a>
        <ul class="dropdown-menu">
            {% for level in content.levels %}
                <li {% if level.name == content.levelName %} class="active"{% endif %}><a
                        href="{{ level.get_absolute_url }}">{{ level.name }}</a></li>
            {% endfor %}
        </ul>
    </li>
{% endblock %}
{% block leftnav %}
    <nav class="leftnav" role="main">
        <ul id="sidenav01" class="accordion nav nav-department nav-tabs nav-stacked">
            <li><a href="#1"><span class="glyphicon glyphicon-time"></span> Schedule</a></li>
            <li>
                <a href="#li02" data-toggle='collapse' data-target='#subnav01' data-parent="#sidenav01"
                   class="accordion-toggle collapsed"><span class="glyphicon glyphicon-user"></span><span
                        class='glyphicon glyphicon-chevron-up pull-right'></span> Classmates</a>
                <ul id="subnav01" class="nav nav-list collapse">
                    <li><a href="#1">Classmate1</a></li>
                </ul>
            </li>

            <li>
                <a href="#li03" data-toggle='collapse' data-target='#subnav02' data-parent='#sidenav01'
                   class="accordion-toggle collapsed"><span class="glyphicon glyphicon-list-alt"></span><span
                        class="glyphicon glyphicon-chevron-up pull-right"></span> Current topics</a>
                <ul id="subnav02" class="nav nav-list collapse">
                    <li><a href="#pimu">Topic1</a></li>
                </ul>
            </li>

        </ul>

    </nav>
{% endblock %}







<section id="main">
    {% block content %}
    {% endblock %}
</section>

templates/basekanji.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}
{% load cache %}
{% block topnav-left %}
    <li><a href="{% url 'note.kanjiviews.kanjiLessons' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Training<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <a href="{% url 'trainingView' %}"><span
                        class="glyphicon glyphicon-star-empty"></span> Kanji</a>
            </li>
        </ul>
    </li>
{% endblock %}

{% block leftnav %}
    <nav class="leftnav" role="main">
        <ul id="sidenav01" class="accordion nav nav-department nav-tabs nav-stacked">
            <li>
                <a href="#li02" data-toggle='collapse' data-target='#subnav01' data-parent="#sidenav01"
                   class="accordion-toggle collapsed"><span class='glyphicon glyphicon-chevron-up pull-right'></span>Classmates</a>
                <ul id="subnav01" class="nav nav-list collapse">
                    <li><a href="#1"><span class="glyphicon glyphicon-home"></span> Schedule</a></li>
                </ul>
            </li>

            <li>
                <a href="#li03" data-toggle='collapse' data-target='#subnav02' data-parent='#sidenav01'
                   class="accordion-toggle collapsed"><span class="glyphicon glyphicon-chevron-up pull-right"></span>Current
                    Kanji</a>


                <ul id="subnav02" class="nav nav-list collapse">
                    {% for kanji in actualKanji %}
                        <li><a href="{{ kanji.get_absolute_url }}"><span
                                class="kanjiCell">{{ kanji.symbol }}</span> {{ kanji.meaning }}</a></li>
                    {% endfor %}

                </ul>

            </li>

        </ul>

    </nav>
{% endblock %}
 {% cache 300 kanji %}{% endcache %}

templates/englishTraining.html
{% extends "baseEnglish.html" %}
{% load bootstrap3 %}
{% load staticfiles %}
{% block custom_inculde %}
{% endblock %}
{% block content %}
    <h3>練習:</h3>
    <div style="text-align: center;">
        <p>{{ content.translation }}</p>

        <p style="font-size: 50px;">{{ content.question }}</p>
    </div>
    <div>
        <form role="answer" id="answerField" style="width: 200px; margin:auto;" class="form-horizontal" method="POST"
              action="" autocomplete="off">
            {% csrf_token %}
            <input type="hidden" value="Answer" name="action">

            <div class="form-group">
                <label></label>
                <input type="text" name="answer" class="form-control" placeholder="答え">
                <span class="help-block"></span>
            </div>
        </form>
    </div>
    {% if content.result %}
        <div style="text-align: center;">
            <h1 style="color:{% if content.result == '正解です' %}green{% else %}red{% endif %};">{{ content.result }}</h1>

            <p>先決問題: <span style="font-size: 25px;">{{ content.prev_question }}</span></p>

            <p>答え: <span style="font-size: 25px;">{{ content.prev_answer }}</span></p>
        </div>
    {% endif %}
    <div>
        <form role="reset" method="post" action="" name="reset" class="form-horizontal">
            {% csrf_token %}
            <input type="hidden" value="Reset" name="action">
            {% buttons %}
                <button type="submit" class="btn btn-default btn-lg center-block">
                    {% bootstrap_icon "remove" %} 練習を終了します
                </button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

templates/examples.html
{% extends "basebunpou.html" %}
{% load bootstrap3 %}
{% block content %}
    <h3>List of bunpou examples for topic <b>{{ content.topicName }}</b> chapter {{ content.lessonNumber }} </h3>
    <table class="table">
        <thead>
        <tr>
            <th></th>
            <th>#</th>
            <th>Kanji</th>
            <th>Kana</th>
            <th>Translation</th>

        </tr>
        </thead>
        <tbody>
        {% for example in content.examplesList %}
            <tr>
                <td><a href="{{ example.get_edit_url }}"><span class="glyphicon glyphicon-edit"></span></a></td>
                <td>{{ forloop.counter }}</td>
                <td>{{ example.kanji }}</td>
                <td>{{ example.furigana }}</td>
                <td>{{ example.translateRus }}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div>

        <form action="" method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="button" id="converter" onclick="convert();" class="btn btn-lg pull-left">
                    {% bootstrap_icon "header" %} Fill Up Hiragana
                </button>
                <button type="submit" class="btn btn-default btn-lg center-block">
                    {% bootstrap_icon "ok" %} Submit Example
                </button>
            {% endbuttons %}

            <script>
                function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie != '') {
                        var cookies = document.cookie.split(';');
                        for (var i = 0; i < cookies.length; i++) {
                            var cookie = jQuery.trim(cookies[i]);
                            // Does this cookie string begin with the name we want?
                            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                }

                function convert(event) {
                    var text = $('#id_kanji').val();
                    $.ajax({
                        type: "POST",
                        async: false,
                        url: '/incul/convert/',
                        data: {"kanji": text, "csrfmiddlewaretoken": getCookie('csrftoken')},
                        dataType: "json",
                        success: function (data) {
                            $('#id_furigana').val(data.message);
                        }
                    });
                    //return ret;
                }

            </script>
        </form>
    </div>



{% endblock %}

templates/userSettings.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
    <h3>User settings</h3>
    <div>
       <form action="" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-default btn-lg center-block">
            {% bootstrap_icon "ok" %} Submit Level
        </button>
        {% endbuttons %}
    </form>
    </div>
{% endblock %}